### ISSUE TITLE
I can not use eio clip when target area is too big

### ISSUE THREAD

**Issue by yuend1004** [bopen/elevation#45]
I found that eio clip causes error when target AOI is located in too many srtm grid. Do you happen to know how we can solve this?

`root@yuend:~/eio_test# eio clip -o srtm.tif --bounds 12.79 40.53 15.42 42.47
Traceback (most recent call last):
  File "/usr/local/bin/eio", line 8, in <module>
    sys.exit(eio())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elevation/cli.py", line 59, in wrapper
    return wrapped(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elevation/cli.py", line 93, in clip
    elevation.clip(bounds, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elevation/datasource.py", line 181, in clip
    datasource_root = seed(bounds=bounds, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elevation/datasource.py", line 150, in seed
    "for how to bulk download tiles." % len(ensure_tiles_names))
RuntimeError: Too many tiles: 12. Please consult the providers' websites for how to bulk download tiles.`

**Comment by ngohikennyyue** [comment]
I tried to change the max_download_tiles number higher but no luck. 
`def seed(cache_dir=CACHE_DIR, product=DEFAULT_PRODUCT, bounds=None, max_download_tiles=9, **kwargs):`
